#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
modifying dpMakeChange
from runestone.academy
https://runestone.academy/runestone/books/published/pythonds/Recursion/DynamicProgramming.html

this improves on original in several ways:
    stores tables of coinCount and coinLastUsed for subsequent calls
    stores coinValueList for subsequent calls:
        necessary if new call involves a different coinValuesList, because then the tables need to be regenerated
    use better variable names
Created on Sat Jan  2 09:51:12 2021
@author: stephankoehler

"""
import time

def dpMakeChange(coinValueList,change):
#=============================================================================
    try:
        if not coinValueList:
            if coinValueList and not dpMakeChange.coinValueList == coinValueList:
                raise
        if len( dpMakeChange.coinCount ) < change + 1:
            dpMakeChange.coinCount.extend( [0]*(change+1) )
            dpMakeChange.coinLastUsed.extend( [0]*(change+1) ) 
    except AttributeError:
        dpMakeChange.coinCount = [0]*(change+1)
        dpMakeChange.coinLastUsed = [0]*(change+1)
        if coinValueList:
            dpMakeChange.coinValueList = coinValueList
        else:
            dpMakeChange.coinValueList = [1]
#============================================================================= 
    for cents in [x for x in range(1, change+1 ) if dpMakeChange.coinCount[x] == 0]:
           dpMakeChange.coinCount[cents] = cents
           dpMakeChange.coinLastUsed[cents] = 1
           for j in [c for c in dpMakeChange.coinValueList if c <= cents]:
                 if dpMakeChange.coinCount[cents-j] + 1 < dpMakeChange.coinCount[cents]:
                    dpMakeChange.coinCount[cents] = dpMakeChange.coinCount[cents-j]+1
                    dpMakeChange.coinLastUsed[cents] = j

       
    remaining_change = change
    list_of_coins = [0]*dpMakeChange.coinCount[change]
    count = 0
    while remaining_change > 0:
        list_of_coins[ count ] = dpMakeChange.coinLastUsed[remaining_change]
        # print(list_of_coins)
        remaining_change = remaining_change - list_of_coins[ count ]    
        count += 1
    return list_of_coins, dpMakeChange.coinCount[change]

def main():
    t = time.time()
    # print( dpMakeChange([1, 5, 10], 21) )
    print( dpMakeChange( [], 21) )
    print( time.time() - t )

main()